pebble:
  suffix: .html
  cache: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: changeme
  main:
    allow-circular-references: false
  sql:
    init:
      mode: always
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: format
      media-types:
        json: application/json
        html: text/html
db-scheduler:
  polling-interval: 1s
